apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: sfdcabe
  description: Salesforce Project

  annotations:
    github.com/project-slug: abepar/sfdcabe
    backstage.io/techdocs-ref: dir:.

  tags:
    - salesforce
    - sfdx
    - apex

  links:
    - url: https://github.com/abepar/sfdcabe
      title: GitHub Repository
      icon: github

    - url: https://developer.salesforce.com/tools/salesforce-dx
      title: Salesforce DX
      icon: docs


spec:
  type: service
  lifecycle: production
  owner: group:guest
  dependsOn: 
    - resource:gitHub
